#!/usr/bin/env php
<?php

include 'src/Dates/BirthDates.php';

$birthDate = "2001-02-06";

$days = new \Yarosh\Dates\BirthDates($birthDate);
$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays\n";
