#!/usr/bin/env php
<?php

$birthDate = "2001-02-06";
$todayDate = date("Y-m-d");

$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalSecs = $todayTime - $birthTime;
$totalDays = floor($totalSecs / 3600 / 24);
echo "$birthDate : $totalDays\n";
