#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

$birthDate = "2001-02-06";

$days = new \Yarosh\Dates\BirthDates($birthDate);
$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays\n";
